name: Build & Deploy MTM
on:
  push:
    branches: [ "main" ]

permissions:
  contents: read
  packages: write

concurrency:
  group: mtm-deploy-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    env:
      VITE_API_URL: https://fineract.kazy.co.tz/fineract-provider
      VITE_TENANT: default

    steps:
      - uses: actions/checkout@v4

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Compute image tags
        id: img
        run: |
          OWNER_LC="$(echo "${GITHUB_REPOSITORY_OWNER}" | tr '[:upper:]' '[:lower:]')"
          echo "image=ghcr.io/${OWNER_LC}/mtm:${GITHUB_SHA}" >> $GITHUB_OUTPUT
          echo "image_latest=ghcr.io/${OWNER_LC}/mtm:main" >> $GITHUB_OUTPUT

      - name: Build & Push image
        uses: docker/build-push-action@v6
        with:
          context: .
          build-args: |
            VITE_API_URL=${{ env.VITE_API_URL }}
            VITE_TENANT=${{ env.VITE_TENANT }}
          push: true
          tags: |
            ${{ steps.img.outputs.image }}
            ${{ steps.img.outputs.image_latest }}

      # Optional: debug SSH before rollout
      - name: Debug SSH (temporary)
        run: |
          echo "${{ secrets.SSH_KEY }}" > id_ci
          chmod 600 id_ci
          ssh -o StrictHostKeyChecking=no -i id_ci ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} "whoami && hostname"

      - name: Roll out to MicroK8s
        uses: appleboy/ssh-action@v1.2.0
        with:
          host:     ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key:      ${{ secrets.SSH_KEY }}
          script: |
            sudo /snap/bin/microk8s.kubectl -n kazy-prod set image deploy/mtm-web web=${{ steps.img.outputs.image }}
            sudo /snap/bin/microk8s.kubectl -n kazy-prod rollout status deploy/mtm-web --timeout=5m
