name: Build & Deploy MTM
on:
  push:
    branches: [ "main" ]
permissions:
  contents: read
  packages: write
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Login GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ secrets.GHCR_USERNAME }}
          password: ${{ secrets.GHCR_TOKEN }}

      - name: Build & Push image
        uses: docker/build-push-action@v6
        with:
          context: .
          build-args: |
            VITE_API_BASE=${{ secrets.VITE_API_BASE || 'https://fineract.kazy.co.tz/fineract-provider' }}
          push: true
          tags: |
            ghcr.io/${{ github.repository_owner }}/mtm:main
            ghcr.io/${{ github.repository_owner }}/mtm:${{ github.sha }}

      - name: Rollout on cluster
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            kubectl -n kazy-prod set image deploy/mtm-web web=ghcr.io/${{ github.repository_owner }}/mtm:${{ github.sha }}
            kubectl -n kazy-prod rollout status deploy/mtm-web --timeout=5m
